api: http://localhost:9123
js_api: http://localhost:9123
mainurl: http://localhost:8080/
pages:
  - description: Overview
    url: /app/overview
    id: tabOverview
  - description: Query
    url: /app/query
    id: tabQuery
  - description: Visualizations
    url: /app/servicegraph
    id: tabServicegraph
  - description: GraphQL
    url: /app/graphql
    id: graphql
  - description: Feed
    url: /app/feed
    id: tabFeed
