api: http://localhost:3000/api/
js_api: http://localhost:3000/api/
mainurl: http://localhost:8025
pages:
  - description: Overview
    url: /app/overview
    id: tabOverview
  - description: ES Query
    url: /app/query
    id: tabQuery
  - description: Visualizations
    url: /app/servicegraph
    id: tabServicegraph
  - description: Feed
    url: /app/feed
    id: tabFeed