api: http://192.168.99.100:9123/
js_api: http://192.168.99.100:9123/
mainurl: http://localhost:8080
pages:
  - description: Overview
    url: /app/overview
    id: tabOverview
  - description: ES Query
    url: /app/query
    id: tabQuery
  - description: Visualizations
    url: /app/servicegraph
    id: tabServicegraph
  - description: GraphQL
    url: /app/graphqlquery
    id: tabGraphqlquery
  - description: Feed
    url: /app/feed
    id: tabFeed
