api: http://localhost:9123/
pages:
  - description: Overview
    url: /app/overview
    id: tabOverview
  - description: Query
    url: /app/query
    id: tabQuery
#  - description: Service Graph
#    url: /app/servicegraph
#    id: tabServiceGraph
  - description: Feed
    url: /app/feed
    id: tabFeed
